import type { Metadata } from "next";
import { InteriorPage } from "@/components/interior-page";
import { artworks } from "@/content/expanded";

export const metadata: Metadata = {
  title: "Vad vi gör | Kockska stiftelserna",
  description: "Läs om lokalt stöd, forskning, stipendier och offentliga konstverk i Trelleborg.",
};

export default function WorkPage() {
  return (
    <InteriorPage eyebrow="Vad vi gör" title="Arvet syns i människor och platser." intro="Stiftelsernas verksamhet rymmer socialt stöd, medicinsk forskning, stipendier och långsiktiga insatser för Trelleborg." source="Verksamhetsuppgifter, stipendiebelopp och konstförteckning är bearbetade från stiftelsernas nuvarande webbplats, kontrollerad 27 september 2026. Belopp och personuppgifter ska verifieras före slutlig lansering.">
      <section className="shell interior-section"><div className="text-split"><p className="eyebrow">01 / Stöd</p><div><h2>För människor och organisationer.</h2><p>Fromma stiftelsens understödsfond fördelar anslag till enskilda och föreningar i Trelleborg. Hemmet för gamla ger bostadsbidrag till äldre och kan bidra till vård av behövande äldre och sjuka.</p><a className="text-link" href="/sok-stod">Se vem som kan söka</a></div></div></section>
      <section className="interior-band"><div className="shell text-split"><p className="eyebrow">02 / Forskning</p><div><h2>Kunskap som kan förbättra vården.</h2><p>Forskningsfonden inriktas på klinisk patientnära forskning inom kroniskt invalidiserande sjukdomar, framför allt artros och kognitiva sjukdomar. På den nuvarande sajten anges att drygt åtta miljoner kronor delas ut årligen till forskning vid skånska institutioner och universitet.</p><p>Under 2026 utlystes dessutom ett tidsbegränsat forskningsmiljöstöd om två miljoner kronor. Två forskningspriser om vardera en miljon kronor tilldelades professor Martin Englund och docent Niklas Mattsson-Carlgren.</p><a className="text-link" href="/sok-stod/medicinsk-forskning">Forskningsmedel och villkor</a></div></div></section>
      <section id="stipendier" className="shell interior-section"><div className="text-split"><p className="eyebrow">03 / Utbildning</p><div><h2>Stipendier och riktade anslag.</h2><div className="fact-stack"><section><h3>Söderslättsgymnasiet</h3><p>Nuvarande webbplats anger elva utmärkelser för studieresultat om 5 000 kronor vardera, ett stipendium om 50 000 kronor till en framstående elev och två stipendier för deltagande i Kemistsamfundets Berzeliusdagar. Skolans stipendiekollegium utser mottagarna.</p></section><section><h3>Musikhögskolor</h3><p>Elever med anknytning till Trelleborg och goda utvecklingsmöjligheter kan nomineras av sin musikhögskola. Nuvarande webbplats anger ett stipendium om 15 000 kronor. Stiftelsens styrelse beslutar.</p></section><section><h3>Kulturskolan i Trelleborg</h3><p>Fem uppmuntringsstipendier om 2 000 kronor och fem om 500 kronor anges på nuvarande webbplats. Kulturskolans kollegium utser stipendiaterna.</p></section><section><h3>Vård och tandvård i Trelleborg</h3><p>Årliga anslag kan gå till forsknings- och utvecklingsarbete, symposier och vidareutbildning vid lasarettet och Folktandvården. Stiftelsernas styrelse fastställer ramarna och respektive verksamhets kommittéer beslutar om fördelningen.</p></section></div></div></div></section>
      <section id="trelleborg" className="interior-band"><div className="shell text-split"><p className="eyebrow">04 / Trelleborg</p><div><h2>Konst och miljöer i staden.</h2><p>Försköningsstiftelsens avkastning ska komma Trelleborgs kommun till del. Stiftelsen deltar i utformningen av utsmyckningar och finansierar enligt nuvarande sajt inte redan beslutade inköp eller konstprojekt.</p><p>Arbetet omfattar även parker och lekplatser, restaurering av Maglarps medeltidskyrka, Rosenträdgården i Stadsparken och andra kulturhistoriska miljöer.</p></div></div></section>
      <section className="shell interior-section" aria-labelledby="works-list"><div className="text-split"><p className="eyebrow">Ur arkivet</p><div><h2 id="works-list">24 dokumenterade insatser.</h2><p>Årtal och plats följer den nuvarande webbplatsens förteckning. Bildrättigheter och upphovspersoner behöver kontrolleras innan ett illustrerat konstarkiv publiceras.</p><ol className="archive-list">{artworks.map(([year, name, place]) => <li key={year + name}><span>{year}</span><strong>{name}</strong><small>{place}</small></li>)}</ol></div></div></section>
    </InteriorPage>
  );
}
